### ISSUE TITLE
Issue with Compiler when deploying code

### ISSUE THREAD

**Issue by jdeniau** [K-Phoen/rulerz#113]
Hi,

Sometime, when we deploy our code, we have the following error:

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: 
"Attempted to load class "Executor_e54f2a89" from namespace "\RulerZ\Compiled\Executor". 
Did you forget a "use" statement for another namespace?"
 at /.../vendor/kphoen/rulerz/src/Compiler/Compiler.php line 47
```

If I read correctly, the compiled class [is generated at runtime](https://github.com/K-Phoen/rulerz/blob/master/src/Compiler/Compiler.php#L66-L84) and is not written to disk (in fact, the bundle cache directory seems to be always empty).

Do you have any idea where it could come from ? 

Thanks !

**Comment by K-Phoen** [comment]
Depending on your configuration, compiled rules are either [evaluated on the fly](https://github.com/K-Phoen/rulerz/blob/5c26c4f99636e4e7e464f1b28c8054b059347534/src/Compiler/EvalEvaluator.php#L23) or [written on disk](https://github.com/K-Phoen/rulerz/blob/5c26c4f99636e4e7e464f1b28c8054b059347534/src/Compiler/FileEvaluator.php#L35) and required.

Assuming that you configured your application to write these classes on disk, I would bet on a bug in the `NativeFilesystem` class. Maybe, for some reason, the cache couldn't be written? I see that errors aren't handled... https://github.com/K-Phoen/rulerz/blob/5c26c4f99636e4e7e464f1b28c8054b059347534/src/Compiler/NativeFilesystem.php

Do you have a way to test that? (I guess that the `NativeFilesystem` class should throw errors)

**Comment by jdeniau** [comment]
Thanks for the hint, I investigate and on our servers the files are generated, but the "bug" do occur when we switch from one server to another.

The bug is ours apparently, I will investigate further though. Thanks for your answer !

Closing as it's not related to rulerz.

**Comment by Leizhengzi** [comment]
@jdeniau I have the same error, have you solved.

**Comment by jdeniau** [comment]
@Leizhengzi It's been a while now, I do not remember exactly where it did come from.
It did probably came from our build system. Possibly the order of the cache warmup and deploy, but I do not remember more, sorry

**Comment by Leizhengzi** [comment]
> @Leizhengzi It's been a while now, I do not remember exactly where it did come from.
> It did probably came from our build system. Possibly the order of the cache warmup and deploy, but I do not remember more, sorry

It's okay. Thanks for your answer!

**Comment by fmartin-lafourchette** [comment]
@Leizhengzi  I have the same error sometimes (not during the deployment), have you solved your issue? Thanks a lot for your help.
