### ISSUE TITLE
Filtering with rules containing parameters failes

### ISSUE THREAD

**Issue by beeare** [K-Phoen/rulerz#13]
Playing with your examples, I get a PHP error when using the `filter` method of the `RulerZ` engine with rules containing parameters.

Sample code to reproduce the issue:

```
<?php
require('../vendor/autoload.php');

use RulerZ\Compiler\FileCompiler;
use RulerZ\Parser\HoaParser;
use RulerZ\Compiler\Target;
use RulerZ\RulerZ;

$playersArr = [
    ['pseudo' => 'Joe',   'gender' => 'M', 'points' => 2500],
    ['pseudo' => 'Moe',   'gender' => 'M', 'points' => 1230],
    ['pseudo' => 'Alice', 'gender' => 'F', 'points' => 9001],
    ['pseudo' => 'Nora',  'gender' => 'F', 'points' => 3450],
    ['pseudo' => 'Lisa',  'gender' => 'F', 'points' => 9540],
];

$compiler = new FileCompiler(new HoaParser());
$rulerz = new RulerZ(
    $compiler, [
        new Target\ArrayVisitor(),
    ]
);
$dynamicRule = 'gender = :gender';
$dynamicRuleParameters = [
    'min_points' => 30,
    'gender'     => 'F'
];
$filteredPlayers = $rulerz->filter($playersArr, $dynamicRule, $dynamicRuleParameters);
```

Executing the code above produces the following PHP error:

> [18-Sep-2015 16:43:41 Europe/Berlin] PHP Parse error:  syntax error, unexpected '-', expecting '{' in C:\Users\brack\AppData\Local\Temp\rulerz_executor_-184339999 on line 6
> [18-Sep-2015 16:43:41 Europe/Berlin] PHP Stack trace:
> [18-Sep-2015 16:43:41 Europe/Berlin] PHP   1. {main}() D:\GitHub Projects\DesignPatternsPHP\src\rulez.php:0
> [18-Sep-2015 16:43:41 Europe/Berlin] PHP   2. RulerZ\RulerZ->filter() D:\GitHub Projects\DesignPatternsPHP\src\rulez.php:62
> [18-Sep-2015 16:43:41 Europe/Berlin] PHP   3. RulerZ\Compiler\FileCompiler->compile() D:\GitHub Projects\DesignPatternsPHP\vendor\kphoen\rulerz\src\RulerZ.php:57

Content of the temp file rulerz_executor_-184339999 from stack trace:

```
<?php
namespace RulerZ\Compiled\Executor;

use RulerZ\Executor\Executor;

class Executor_-184339999 implements Executor
{
    use \RulerZ\Executor\ArrayTarget\FilterTrait;
    use \RulerZ\Executor\ArrayTarget\SatisfiesTrait;

    protected function execute($target, array $operators, array $parameters)
    {
        return $target["gender"] == $parameters["gender"];
    }
}
```

**Comment by K-Phoen** [comment]
Thanks for reporting this issue :+1: 

It should be fixed by [this commit](https://github.com/K-Phoen/rulerz/commit/c14165476ed1dacf032becc5d004c1183cb9931b), feel free to reopen the issue if it's not.

**Comment by beeare** [comment]
Thank you, it works as expected now. :+1:
