### ISSUE TITLE
Issue with the FileCompiler and Elasticsearch

### ISSUE THREAD

**Issue by mnapoli** [K-Phoen/rulerz#14]
Hi, here is the code generated by the FileCompiler when calling `filter()` for the following rule `price = 30` (`$rulerz->filter($elasticsearch, 'price = 30', [], $context)`):

``` php
<?php
namespace RulerZ\Compiled\Executor;

use RulerZ\Executor\Executor;

class Executor_3f155154 implements Executor
{
        use \RulerZ\Executor\Elasticsearch\ElasticsearchFilterTrait;
        use \RulerZ\Executor\Polyfill\FilterBasedSatisfaction;

    protected function execute($target, array $operators, array $parameters)
    {
        return Array;
    }
}
```

As you can see, there's an error: `execute()` returns `Array` ([the compiled rules seem to be an array instead of a string](https://github.com/K-Phoen/rulerz/blob/master/src/Compiler/AbstractCompiler.php#L46)).

I believe (I might be wrong) that this is because the elasticsearch implementation [returns arrays (instead of strings) for operators](https://github.com/K-Phoen/rulerz/blob/master/src/Compiler/Target/Elasticsearch/GenericElasticsearchVisitor.php#L41).

Am I doing something wrong here? Here is the configuration of RulerZ:

``` php
$compiler = new RulerZ\Compiler\FileCompiler(new RulerZ\Parser\HoaParser);
$rulerz = new RulerZ\RulerZ($compiler, [
    new RulerZ\Compiler\Target\Elasticsearch\ElasticsearchVisitor,
])
```

**Comment by K-Phoen** [comment]
Hi!

Thanks for taking the time to make such a great bug report :+1: 
I could reproduce the issue. You were right: the compiled rule is returned as an array (the elasticsearch query) while it should be returned as a string.

I'll try to fix that and make a new release tonight.

**Comment by mnapoli** [comment]
That rocks thank you! Let me know if I can help!

**Comment by K-Phoen** [comment]
I started to work on a fix (the elasticsearch-related targets were really badly broken). You can checkout the [fix-elasticsearch](https://github.com/K-Phoen/rulerz/tree/fix-elasticsearch) branch, I didn't update the tests yet but it should work better than master.

**Comment by mnapoli** [comment]
Thanks! I've tried to run with a similar fix (but way more hacky) and run into another issue `$rulerz->filter()` retuns the whole response of elasticsearch (not just the "hits").

I'm trying to run tests locally to contribute a few things, are you interested in a PR to add a vagrant config? (I work on this in a VM instead of installing everything locally)

**Comment by K-Phoen** [comment]
Returning the whole response was done on purpose: I didn't want to temper with the results returned by the elasticsearch client. But now I do think that only the hits should be returned.

By default, the return type for all the targets should be the same (the results with no metadata/noise).

And yeah, a vagrant config would definitely be great! I work with docker containers, I guess I could provide a few scripts to integrate them in this repo.

**Comment by mnapoli** [comment]
> By default, the return type for all the targets should be the same (the results with no metadata/noise).

+1

But that would mean coming up with an abstract representation of "what is returned by `filter()`". Because if the rules match 100 000 records we don't want them loaded in memory at once, and because we can't use each backend's pagination (e.g. Doctrine/SQL limit, Elasticsearch pagination, etc.) since the result should always be of the same type.

What's needed as a result of `filter()` is:
- the number of results
- the results lazily loaded

It could be implemented with (for example) PHP 5.5 generators. For example:

``` php
interface FilterResult
{
    public function getCount();
    public function getIterator();
}
```

`getIterator()` could return a generator (using `yield`) that allows to traverse all the results while not loading them all in the memory at once.

I have some time now, I could look into this if that's an approach that you find OK (it would mean to require PHP 5.5 though).

**Comment by mnapoli** [comment]
@K-Phoen I started looking into the idea I described: https://github.com/wizacha/rulerz/commits/results

This is very messy, mainly because I'm discovering phpspec and it doesn't seem very practical to write functional tests (maybe I'm wrong), and also because I just want to make elasticsearch work at first. What do you think of the `FilterResult` class? It could be useful to iterate lazily on all the results of the match.

**Comment by K-Phoen** [comment]
I close this issue as both the elasticsearch targets and the "return values"-related issues are fixed.
