### ISSUE TITLE
Add Solr support

### ISSUE THREAD

**Issue by Hywan** [K-Phoen/rulerz#22]
Hello!

Is it possible to add Solr support?
Maybe we should split rulerz into rulerz-core and rulerz-driver-solr, rulerz-driver-elasticsearch, rulerz-driver-doctrine & co.?

Thoughts?

**Comment by K-Phoen** [comment]
Hi!

It should be possible, yeah :)
Do you use a specific PHP library? Maybe [solariumphp/solarium](https://github.com/solariumphp/solarium)?

Concerning a split, I already thought about it and I think that I'll stabilize the library first. It's easier for me to work (and rework) the code if it's in the same place.

**Comment by Hywan** [comment]
@K-Phoen Yup, solarium is a good choice.

**Comment by pstephenson02** [comment]
+1 for this

**Comment by K-Phoen** [comment]
I started a PR for this, you can follow the progress here: https://github.com/K-Phoen/rulerz/pull/23

**Comment by K-Phoen** [comment]
Merged and released, see 0.16.0
