### ISSUE TITLE
doctrine < 2.5 does not support embedds

### ISSUE THREAD

**Issue by kandelyabre** [K-Phoen/rulerz#32]
Undefined property: Doctrine\ORM\Mapping\ClassMetadata::$embeddedClasses
https://github.com/K-Phoen/rulerz/blob/master/src/Executor/DoctrineQueryBuilder/AutoJoin.php#L122
https://github.com/K-Phoen/rulerz/blob/master/src/Executor/DoctrineQueryBuilder/AutoJoin.php#L149

**Comment by K-Phoen** [comment]
It should be fixed now. Thanks for taking the time to report this and sorry for the delay :)
