### ISSUE TITLE
Generator Object response

### ISSUE THREAD

**Issue by Gu3** [K-Phoen/rulerz#34]
Hi ! I start to try RulerZ with a simple example in a repository : 

``` php
<?php
// src/AppBundle/Entity/Person/Repository/PersonRepository.php
namespace AppBundle\Entity\Person\Repository;

use Doctrine\ORM\EntityRepository;
use RulerZ\Compiler\FileCompiler;
use RulerZ\Parser\HoaParser;
use RulerZ\Compiler\Target;
use RulerZ\RulerZ;

class PersonRepository extends EntityRepository
{
    public function testRule(){
        // compiler
        $compiler = new FileCompiler(new HoaParser());
        $rulerz = new RulerZ(
            $compiler, [
                new Target\ArrayVisitor([
                    'length' => 'strlen'
                ]),
            ]
        );

        $users = [
            ['pseudo' => 'Joe',   'gender' => 'M', 'points' => 40],
            ['pseudo' => 'Moe',   'gender' => 'M', 'points' => 20],
            ['pseudo' => 'Alice', 'gender' => 'F', 'points' => 60],
        ];

        $rule  = 'gender = :gender';
        $parameters = [
            'gender' => 'F',
        ];

        echo '<pre>';
        var_dump($rulerz->filter($users, $rule, $parameters));
        echo '</pre>';
        exit();
    }
}

?>
```

I just have "object(Generator)[919]" as answer.
any ideas what I forgot ?
Thanks !

Cheers. 
Vincent.

**Comment by K-Phoen** [comment]
Hi!

The `filter` method returns something that is [`Traversable`](http://php.net/manual/en/class.traversable.php). It means that we can iterate over it with a `foreach` statement:

``` php
$rule  = 'gender = :gender';
$parameters = [
    'gender' => 'F',
];

echo '<pre>';
foreach ($rulerz->filter($users, $rule, $parameters) as $user) {
    var_dump($user);
}
echo '</pre>';
```

Generators are an efficient way to iterate through a (potentially) large data-set without having to store all the data in memory. You can find more information on them in [PHP's documentation](http://php.net/manual/en/language.generators.overview.php).

**Comment by K-Phoen** [comment]
I close this issue as the behavior you observe seem totally valid but do not hesitate to ask more questions if you need to :)

**Comment by Gu3** [comment]
Thank you for the quick answer ! foreach was the solution :)

**Comment by C-Duv** [comment]
[The documentation](https://github.com/K-Phoen/rulerz/blob/c2ff3f8/doc/filter.md#filter-your-target) seems to indicate calling `var_dump()` directly on the result of `filter()` returns the desired results, which is clearly not the case.

Thanks for opening the issue @Gu3: I had the same unexpected behavior (getting *class Generator#61 (0) {}* results).

One solution to get an `array` is to use [`iterator_to_array()`](http://php.net/manual/function.iterator-to-array.php).

**Comment by K-Phoen** [comment]
You're right, the documentation should have been clearer. I updated it :)
