### ISSUE TITLE
Fos Elastica

### ISSUE THREAD

**Issue by Gu3** [K-Phoen/rulerz#35]
Hi ! 
Do you ever use Rulerz with FOS Elastica ? 
I am blocked here : 

`$search = new Elastica\Search($client);`

I don't know wich services I need to use, if you have any Ideas, I take it :)

Thanks,

Vincent.

**Comment by K-Phoen** [comment]
The [cookbook section dedicated to Elastica](https://github.com/K-Phoen/rulerz/blob/master/doc/cookbooks/ruflin_elastica.md) should be useful :)

**Comment by Gu3** [comment]
Yep I saw this cookbook. As I said on the previous message : I am blocked on the section $search =...
It was just in case you do that before :)

Thank you again for your answer (always quick) ! Appreciate it ! :)

**Comment by Gu3** [comment]
I've got the right answer : 
`$search = $this->container->get('fos_elastica.index.app');`
But I didn't clear the cache... :-1: 

Subject close :)
