### ISSUE TITLE
UI: get parameters and highlight code

### ISSUE THREAD

**Issue by 1e1** [K-Phoen/rulerz#39]
I write a rule manager for the end-users. 
How can I extract all parameters from a rule like `user.group in :group`?
I would like to generate the form which it asks a value for each parameter. 
I can do it with a regexp: `\b:\w+\b` but I'm not sure that it matches exactly like the RuerZ pattern. Moreover this function should be in the same workspace as the other RulerZ tools. 

Ahead this form, I display the rule. 
But some complex rules are difficult to read. How can I colorize it? (highlighting keywords, parameters, opertator…)

Thanks

**Comment by K-Phoen** [comment]
> How can I extract all parameters from a rule like `user.group in :group`?

I already done something similar in [the `RuleValidator` class](https://github.com/K-Phoen/rulerz-bridge/blob/master/Validator/Constraints/RuleValidator.php): I check that no unknown variable or operator is used in a rule. You could use this class as a source to retrieve the list of the parameters used in a rule. It would look like:

``` php
$parser = new \RulerZ\Parser\HoaParser();
$ruleModel = $parser->parse($rule); // this builds an in-memory representation (an AST) of the textual rule $rule
var_dump($ruleModel->getParameters());
```

This works since version 0.19.0 :)

> How can I colorize it?

Right now, I don't have a solution for this. I guess that you could use something like [highlight.js](https://highlightjs.org/) to add syntactic colorization for the rules. You would need to write a plugin to add support for RulerZ grammar though (I could work on that, it seems fun).

**Comment by 1e1** [comment]
1/ Thanks! 
But kphoen/rulerz-bundle is still on 0.12.0… I work on Symfony3. 

2/ I will look that :)

**Comment by K-Phoen** [comment]
> But kphoen/rulerz-bundle is still on 0.12.0… I work on Symfony3. 

kphoen/rulerz-bundle:0.12.0 should allow rulerz:0.19.0, so it should not be a problem :)

**Comment by K-Phoen** [comment]
For the highlight.js thing, you might be able to use the SQL coloration as RulerZ's DSL is very similar to the SQL ;)

**Comment by 1e1** [comment]
I added `"kphoen/rulerz": "^0.22.0"` in my composer.json, then I updated: 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package kphoen/rulerz could not be found in any version, there may be a typo in the package name.
  Problem 2
    - kphoen/rulerz-bundle 0.12.0 requires kphoen/rulerz ~0.17 -> no matching package found.
    - kphoen/rulerz-bundle 0.11.1 requires kphoen/rulerz ~0.1, >=0.13.0 -> no matching package found.
    - kphoen/rulerz-bundle 0.12.0 requires kphoen/rulerz ~0.17 -> no matching package found.
    - Installation request for kphoen/rulerz-bundle >=0.11.1 -> satisfiable by kphoen/rulerz-bundle[0.11.1, 0.12.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by K-Phoen** [comment]
That's because the version 0.22.0 does not exist :)
The most recent version is 0.19.0.

Try adding `"kphoen/rulerz": "^0.19.0"`

**Comment by 1e1** [comment]
Damned! :p 

Wünderbar! 
I need exactly the array keys:

```
        $parser = new HoaParser();
        $ruleModel = $parser->parse($this->expression);

        return array_keys($ruleModel->getParameters());
```

**Comment by K-Phoen** [comment]
I close this issue then. Feel free to reopen it if needed :)
