### ISSUE TITLE
[Support]Use rules with joined entities

### ISSUE THREAD

**Issue by BboyKeen** [K-Phoen/rulerz#41]
Hi,

Looks like the docs are only mentioning the usage of simple entities when defining rules.

But can I use more complex rules with joined entities ?
Should I prepare the query builder with joins ?

Will I be able to use the filter to check entity satisfaction ?

Thanks

**Comment by K-Phoen** [comment]
Hi,

I completed a bit the documentation to explain [how can joins be handled](https://github.com/K-Phoen/rulerz/blob/master/doc/cookbooks/doctrine_orm.md#handling-joins).

> But can I use more complex rules with joined entities ?
> Should I prepare the query builder with joins ?

Short answer: you can use joined entities in your rules and if you don't prepare your query builder, RulerZ will try to automatically join the entities used in your rule.

It should also work to check entity satisfaction.

I close this issue but do not hesitate to reopen it if you have more questions or if the documentation isn't clear enough :)

**Comment by ghost** [comment]
Your explanations are great, thank you.
I'll try to use it later and come back here if I have any problem.

**Comment by BboyKeen** [comment]
Sorry, I didn't notice I was logged in with another account.
