### ISSUE TITLE
Complex queries

### ISSUE THREAD

**Issue by estahn** [K-Phoen/rulerz#42]
Hi @K-Phoen,

Just wondering if "complex" doctrine  queries are possible with the current specification implementation.

Something like this:

``` SQL
SELECT p
FROM Entity:Product p
JOIN p.categories c1
WHERE NOT EXISTS (
    SELECT c2
    FROM Entity:Category c2
    WHERE c2.lft <= c1.lft AND
          c2.rgt >= c1.rgt AND
          c2.status = 'deleted'
)
```

It basically filters categories that have inactive ancestors.

Also, how to implement something like this with RulerZ:

`Spec::lt('startDate', new \DateTime('-4weeks'))`

**Comment by K-Phoen** [comment]
I doubt that this kind of "complex" query is easily doable in the current state of the things. I guess that supporting subqueries for SQL-related targets could be done but also supporting it for other targets could be difficult.

For the `Spec::lt('startDate', new \DateTime('-4weeks'))` spec, you could write something like this:

``` php
Spec::lt('startDate', (new \DateTime('-4weeks'))->format(\DateTime::ISO8601));
```

Or we could imagine creating a new date-oriented specification :

``` php
Spec::dateLt('startDate', new \DateTime('-4weeks'));
```

**Comment by estahn** [comment]
@K-Phoen I solved our problem without the specification pattern by creating composable Doctrine Query Builder objects.
