### ISSUE TITLE
Security and SQL injection

### ISSUE THREAD

**Issue by VincentClair** [K-Phoen/rulerz#43]
Thanks for this awesome library.

I have a question about security: if I use a app that construct a rule on front-end and send it to the back-end to make request on a database. Need I validates values from injections ? The Ruler compiler could only give String, Boolean, Float, Int. The only problem could come from String. But as I use prepare queries and inject values by parameters, I think there could not be a vulnerability.
Am I right ? Do you see other problems ?

**Comment by K-Phoen** [comment]
If you use parameters in your rules, it should be fine. RulerZ will also use parameters when it comes to querying the database so injections should not be a problem here :)

**Comment by VincentClair** [comment]
Thanks for your reply :)

**Comment by K-Phoen** [comment]
You're welcome :)

I close this issue then.
