### ISSUE TITLE
Test rules to make sure they are valid

### ISSUE THREAD

**Issue by mnapoli** [K-Phoen/rulerz#50]
When a UI is responsible for generating some rules, we need to make sure they are valid (that they will execute correctly). Is there a way to "test" that some rules are valid?

What I thought of is trying to compile them with the compiler that Rulerz uses, but:
- is that enough to make sure they are valid (i.e. no syntax errors)
- in `$compiler->compile($rule, $targetCompiler)` can I simply use `ArrayVisitor` (most basic one) or do I need to set up something more complex?

And finally would it make sense to add that to Rulerz directly?

**Comment by mnapoli** [comment]
What I did for now and that seems to work:

``` php
        try {
            $this->rulerzCompiler->compile($rules, new ArrayVisitor);
        } catch (UnexpectedToken $e) {
            throw new InvalidRules('Invalid promotion rules: ' . $rules, 0, $e);
        }
```

**Comment by K-Phoen** [comment]
> Is there a way to "test" that some rules are valid?

To consider a rule as "valid", it must:
- be syntactically correct
- use only existing operators
- use only existing variables/accesses

I've already implemented these verifications in [wallabag](https://github.com/wallabag/wallabag/pull/1478) to check that the tagging rules written by users are valid.

I've written a [`RuleValidator`](https://github.com/K-Phoen/RulerZBundle/blob/3d07954ab14016a4c6a62ab072694537556220a4/Validator/Constraints/RuleValidator.php) that compiles the rule, and I use the resulting model to check that all the used variables and operators are allowed. As there is no way to automatically know which variables and operators are allowed, I used [a whitelist](https://github.com/wallabag/wallabag/blob/a707643ef1a0d5f1cf4ab9826492f4c9cb2d8c09/src/Wallabag/CoreBundle/Entity/TaggingRule.php#L31-L34).

**Comment by K-Phoen** [comment]
@mnapoli do you need additional input on this?

**Comment by mnapoli** [comment]
Nope thanks, we've used the trick I shown above for now.
