### ISSUE TITLE
Positional parameters numbering not starting from 0 if Parser used multiple times for DoctrineORMVisitor

### ISSUE THREAD

**Issue by malef** [K-Phoen/rulerz#52]
First of all, let me say that I like this library very much! I'm just getting to know it (after a nice workshop on PHPCon Poland) but it is something that I was trying to pursue in some of my own projects for building database queries. Your version is much more generic superior to what I was able to achieve though. Kudos to you!

I've been playing around with `master` version (together with RulerZBundle) and positional parameters (as I need to apply same specification few times) when I noticed that if I use `Parser` twice in a single request (e.g. by filtering with different specifications on two different targets) positional parameters are not numbered correctly in case of a second and following queries. Assuming that the first query has three such parameters I'm getting `?0`, `?1` and `?2` as expected, but for the second query I'm getting `?3`, which causes exception when Doctrine tries to execute the query (as the parameters array has only key equal to `0`).

The line responsible for this is https://github.com/malef/rulerz/blob/master/src/Parser/Parser.php#L184 - I suppose a new `Parser` instance should be created each time, or the counter should be reset. At the moment I've just started diving into the details of this library so I can't propose a proper PR with fix yet, but maybe I will do it in the future.

At the same time I would also like to know your opinion on replacing parameter names with some unique strings instead of using positional parameters. The latter solution probably won't work if RulerZ will receive a `queryBuilder` instance for which some positional parameters are already used, as it starts numbering from 0, effectively overriding them. In solutions I was trying to implement I was trying to isolate as much as possible from parameters that may have been added before, usually by adding some value provided by `uniqid`. (It was mostly because different specifications were comming from different parts of applications which were not aware of each other.) I've tried it also with this library while using version `0.19.1` (by generating unique parameter names inside each instance of `Specification`) and it allowed me to repeat same specification multiple times, but I'm pretty sure it messes up caching and probably some other things. Do you think this approach would be feasible in case of this library or do you want to take another route?

**Comment by K-Phoen** [comment]
Thanks! 👍 
It's always a pleasure to receive feedback from a user :)

Concerning your issue, you're right: the counter should be reset. I'll work on a fix in the next days.

Handling parameters is quite hard. Positional parameters are causing troubles and replacing parameters names isn't as easy as it sounds.

I think that parameters management is one of the part in this library that needs a refactoring, but I just don't know how to refactor it yet :)

> I've tried it also with this library while using version 0.19.1 (by generating unique parameter names inside each instance of Specification) and it allowed me to repeat same specification multiple times, but I'm pretty sure it messes up caching and probably some other things

This is usually the approach I use. Parameters named are not random, just unique, so the cache shouldn't be a problem here.

**Comment by K-Phoen** [comment]
The positional parameter numbering issue should be fixed in master.

A refactoring should be done to have a cleaner management of the parameters, but I don't know – yet – how to do it. I'll think about it and create an issue for that later.

Thanks again for your feedback, I'm glad that you find RulerZ interesing/useful and I'd be happy to have more feedback on what you use it for :)
