### ISSUE TITLE
Duplicate auto joins for DoctrineORMVisitor

### ISSUE THREAD

**Issue by malef** [K-Phoen/rulerz#53]
When I'm using a complex composite specification on `master` branch that uses some autojoin multiple times then for `DoctrineORMVisitor` detected joins include duplicates. E.g. if my rule contains sections like `foo.id = ? AND foo.name = ?` it results in two joins to `foo` table, both having the same alias like `_3_foo`. This results in Doctrine throwing an exception when query is executed as same alias for join is used multiple times (e.g. there are two identical `LEFT JOIN`s with the same alias).

Am I doing something wrong here? For now I did a simple workaround just to keep me going (you can have a look at it at https://github.com/malef/rulerz/commit/28f8ac1c8291525e0bf8633124f26ac780ffa697) but I'm not sure if this is a bug or if I'm misusing this library.

**Comment by K-Phoen** [comment]
It's probably a bug as this portion of the code isn't very stable. I should have time to look into this issue during the week-end, thanks for taking the time to report it!

**Comment by bobdercole** [comment]
I am also experiencing the same issue. The fix at malef@28f8ac1c8291525e0bf8633124f26ac780ffa697 is working for me.

**Comment by iainmckay** [comment]
@K-Phoen Can we possibly get this fix merged in? We're also running in to the same issue and malef's fix resolves the issue.

**Comment by pioneer32** [comment]
Currently, we're facing the same issue. +1 for merging ASAP.

**Comment by ghost** [comment]
Same here, Please merge ASAP.

**Comment by K-Phoen** [comment]
This bug waited way too much time to be addressed, sorry about that.

I investigated it a bit and came up with a fix (I hope). It would be awesome if someone had time to test the fix in #73
