### ISSUE TITLE
Where could I find the Expr related file and code?

### ISSUE THREAD

**Issue by xeoshow** [K-Phoen/rulerz#55]
Hi,

I am new to rulerz, found there is a file named using_spec_builder.php in folder \examples, but when I trying to run it, can not find dependency for below code. How could I resolve the problem? Thanks!

$spec = Expr::andX(
    Expr::equals('gender', 'F'),
    Expr::moreThan('points', 3000)
);

**Comment by xeoshow** [comment]
And also, where could I find a simple and complete single test php file which have no any extra dependency ?

**Comment by K-Phoen** [comment]
Hello,

The specification builder is here: https://github.com/K-Phoen/rulerz-spec-builder

If you are looking for usage examples, the documentation should provide you the information you need (if it doesn't, it's a problem ^^). If you want *ready to run* examples, you can start with `.examples/using_textual_rules.php` (and maybe comment the doctrine-related code).

**Comment by K-Phoen** [comment]
Closing this since there is no new question. Feel free to reopen the issue if needed :)
