### ISSUE TITLE
Why ExecutionContext is immutable ?

### ISSUE THREAD

**Issue by syrm** [K-Phoen/rulerz#57]
In my FilterTrait i want to inject metadata in ExecutionContext.
Right now i pushing metadata in parameters :  $parameters['ting.metadata'] = $repository->getMetadata();

But i think metadata is more context related than parameters related.
So is there any reason to make ExecutionContext immutable ?

**Comment by K-Phoen** [comment]
The execution context can be specified when you call RulerZ (example: https://github.com/K-Phoen/rulerz/blob/master/src/RulerZ.php#L80). Isn't this sufficient to inject your metadata?

**Comment by syrm** [comment]
No its not.
```php
        $feeds = $this->get('domain.ting.rulerz')->filterSpec($feedRepository, new Not(new IsEnabled()), ['limit' => 10]);
```

FilterTrait
```php
    public function filter($repository, array $parameters, array $operators, ExecutionContext $context)
    {
        /** @var Repository $repository */
        if ($repository instanceof MetadataProvider) {
            $parameters['ting.metadata'] = $repository->getMetadata();
        }
```

It's more cleaner if FilterTrait has the responsability to know how to do a filter on the repository given.

**Comment by syrm** [comment]
So ? :-)

**Comment by K-Phoen** [comment]
I don't know what you want to achieve or what these metadata are useful for, but if you want to store them in the execution context, this should do it:

```php
$feeds = $this->get('domain.ting.rulerz')->filterSpec($feedRepository, new Not(new IsEnabled()), [
    'limit' => 10,
    'ting.metadata' => $feedRepository->getMetadata(),
]);
```

And in your `FilterTrait` (that should be used in your executor I guess), you could use it like this:

```php
public function filter($repository, array $parameters, array $operators, ExecutionContext $context)
{
    $metadata = $context['ting.metadata'];

    // …
}
```

**Comment by syrm** [comment]
Like i said : It's more cleaner if FilterTrait has the responsability to know how to do a filter on the repository given.

**Comment by K-Phoen** [comment]
What do you use `$parameters['ting.metadata']` for?

**Comment by syrm** [comment]
To build my QueryBuilder, but nevermind, i build my own rules system for Ting.
