### ISSUE TITLE
Latest "patch" version introduced breaking changes :-(

### ISSUE THREAD

**Issue by j0k3r** [K-Phoen/rulerz#61]
Looks like 0.19.3 (which should be a safe patch release) has a lot of breaking changes.
The wallabag build is broken since the release of that version.
https://travis-ci.org/wallabag/wallabag/jobs/195144905#L531

> Fatal error: Class 'RulerZ\Compiler\Target\ArrayVisitor' not found

Unless there is no modification to apply in wallabag to fix that problem, I think it's better to release 1.0.0 instead of simple patch / minor release.

**Comment by nicosomb** [comment]
Hello @K-Phoen! 

Any news about this issue?

**Comment by K-Phoen** [comment]
A while back, I started a cleanup of this lib that didn't get released. I forgot about it and released the 0.19.3 version when I should have released a 0.20.0… sorry about that.

I'll try to find some time today to fix this mess in the library, the bundle and ultimately I'll make a PR to wallabag for the few things that will need to change on your side (nothing much, really).

I don't want to release a 1.0.0 version for now as there are still a thing or two that need to be done regarding how the operators are managed.

Again, I'm really sorry for the trouble.
