### ISSUE TITLE
Get SQL where clause for native query

### ISSUE THREAD

**Issue by anthonydessalles** [K-Phoen/rulerz#64]
Hello,

I would like to use RulerZ library in a legacy environment and I need to apply a formatted rule into a pure SQL query.
Can you tell me how can I get a formatted rule like the "execute" method directly without passing it to the "satisfied" nor "filter" methods ?

Thanks for helping.

Cordially,
Anthony Dessalles

**Comment by K-Phoen** [comment]
Hello,

I think that the easiest way to achieve that would be to create your own compilation target. You can use the [`DoctrineDBAL` target](https://github.com/K-Phoen/rulerz/blob/96caaad9c28d77b5a2a440e6f0f42acaa3c6ed11/src/Target/DoctrineDBAL/DoctrineDBAL.php) as reference. This would allow you to use the `filter` method directly on your DBAL, as you would do with any other target.

For your reference, this is the part of the DoctrineDBAL target that receives the compiled SQL code: https://github.com/K-Phoen/rulerz/blob/96caaad9c28d77b5a2a440e6f0f42acaa3c6ed11/src/Executor/DoctrineDBAL/FilterTrait.php#L21

**Comment by anthonydessalles** [comment]
Thanks a lot
