### ISSUE TITLE
Alias Conflict with Doctrine Auto Join

### ISSUE THREAD

**Issue by bobdercole** [K-Phoen/rulerz#79]
Hello,

I am trying to filter entities with the DoctrineOrm target. I've ran into a very particular issue where the auto join code attempts re-use an already defined alias, resulting in a Doctrine QueryException. I am using the latest version (0.20.4) of RulerZ. Here are the conditions in which this occurs:

- The entity has two associations.
- The associations themselves have additional associations.
- The additional associations are of the same entity.
- The additional association names are the same. I'm not sure if this is relevant.
- The filter involves the additional associations.

Here is a simple example of the association map:

- User [of type User]
    - Groups [of type Group]
        - Owner [of type Person]
    - Places [of type Place]
        - Owner [of type Person]

When I filter on the user group owner id and the user place owner id, the auto join code assigns both associations the same alias.

I've narrowed the culprit down to [this line](https://github.com/K-Phoen/rulerz/blob/025d27eef296b67d24b78d006d31cc756e36afe0/src/Target/DoctrineORM/DoctrineAutoJoin.php#L87). I found that adding more specificity to the alias name resolves the issue. For example, I've done the following as a workaround:

```php
$alias = sprintf('_%d_%s', count($this->knownEntities, COUNT_RECURSIVE), $dimension);
```

Let me know your thoughts. I can open a pull request, but I'm not sure if this is the best fix.

**Comment by K-Phoen** [comment]
The proposed fix seems plausible to me :)

In the absence of tests for this class, I won't ask you to write some (note to self: this class really needs to be tested…).

I'll trust you when you say it works in your application. If the tests are still green, I will test in my applications that it doesn't break anything and merge your PR.

P.S : thanks for this really detailed issue 👍

**Comment by Shandur** [comment]
@K-Phoen Is it supposed to be merged?
