### ISSUE TITLE
Using spaces in identifiers

### ISSUE THREAD

**Issue by nirix** [K-Phoen/rulerz#97]
We use RulerZ to filter arrays and databases, sometimes with the same rule(s) and have no control over how the identifiers/indexes/columns are formatted.

The data we receive can have columns such as `First Name` or `Category - A (Level 1)`.

I've read through the documentation and code and there doesn't appear to be any support for identifiers with spaces.

Would it be possible to have support for identifiers with spaces added?

**Comment by K-Phoen** [comment]
Hello,

You are absolutely right, spaces are currently not supported in identifiers and it probably won't change. It's a rather unusual need and I think it would be difficult to consistently implement it for all the supported targets.
